spring.application.name=facesmash
spring.datasource.url=jdbc:postgresql://localhost:5432/facesmash
spring.datasource.username=ligfi
spring.datasource.password=0505
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.servlet.multipart.max-file-size= 20MB
spring.servlet.multipart.max-request-size=20MB